# Generated by Django 4.2.7 on 2023-11-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTrustRegionSQPParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improve_ratio_threshold', models.FloatField()),
                ('min_trust_box_size', models.FloatField()),
                ('min_approx_improve', models.FloatField()),
                ('min_approx_improve_frac', models.FloatField()),
                ('max_iter', models.FloatField()),
                ('trust_shrink_ratio', models.FloatField()),
                ('trust_expand_ratio', models.FloatField()),
                ('cnt_tolerance', models.FloatField()),
                ('max_merit_coeff_increases', models.FloatField()),
                ('max_qp_solver_failures', models.IntegerField()),
                ('merit_coeff_increase_ratio', models.FloatField()),
                ('max_time', models.FloatField()),
                ('initial_merit_error_coeff', models.FloatField()),
                ('inflate_constraints_individually', models.BooleanField()),
                ('trust_box_size', models.BooleanField()),
                ('log_results', models.BooleanField()),
                ('log_dir', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trajopt_basic_trust_region_sqp_parameters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollisionConstraintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('use_weighted_sum', models.BooleanField(verbose_name=False)),
                ('type', models.CharField(choices=[('0', 'Single Timestep'), ('1', 'Discrete Continuous'), ('2', 'Cast Continuous')], default='1', max_length=255)),
                ('safety_margin', models.FloatField(default=0.01)),
                ('safety_margin_buffer', models.FloatField(default=0.05)),
                ('coeff', models.FloatField(verbose_name=20)),
            ],
            options={
                'db_table': 'trajopt_collision_constraint_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollisionCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('use_weighted_sum', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('0', 'Single Timestep'), ('1', 'Discrete Continuous'), ('2', 'Cast Continuous')], default='1', max_length=255)),
                ('safety_margin', models.FloatField(default=0.025)),
                ('safety_margin_buffer', models.FloatField(verbose_name=0.0)),
                ('coeff', models.FloatField(verbose_name=20)),
            ],
            options={
                'db_table': 'trajopt_collision_cost_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrajOptDefaultPlanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartesian_coeff', models.JSONField(default={'data': [1, 1, 5]})),
                ('joint_coeff', models.JSONField(default={'data': [1, 1, 5]})),
                ('term_type', models.CharField(choices=[('1', 'Tt Cost'), ('2', 'Tt Cnt'), ('4', 'Tt Use Time')], default='2', max_length=255)),
            ],
            options={
                'db_table': 'trajopt_default_plan_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrajOptDefaultSolverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convex_solver', models.CharField(choices=[('GUROBI', 'Gurobi'), ('OSQP', 'Osqp'), ('QPOASES', 'Qpoases'), ('BPMPD', 'Bpmpd'), ('AUTO_SOLVER', 'Auto Solver')], default='OSQP', max_length=255)),
                ('convex_solver_config', models.TextField(default=None, max_length=10000)),
                ('opt_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.basictrustregionsqpparameters')),
            ],
            options={
                'db_table': 'trajopt_default_solver_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrajOptDefaultCompositeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_test_type', models.CharField(choices=[('0', 'First'), ('1', 'Closest'), ('2', 'All'), ('3', 'Limited')], default='2', max_length=255)),
                ('smooth_velocities', models.BooleanField(default=True)),
                ('velocity_coeff', models.JSONField(default={'data': []})),
                ('smooth_accelerations', models.BooleanField(default=True)),
                ('acceleration_coeff', models.JSONField(default={'data': []})),
                ('smooth_jerks', models.BooleanField(default=True)),
                ('jerk_coeff', models.JSONField(default={'data': []})),
                ('avoid_singularity', models.BooleanField(default=False)),
                ('avoid_singularity_coeff', models.FloatField(default=5.0)),
                ('longest_valid_segment_fraction', models.FloatField(default=0.01)),
                ('longest_valid_segment_length', models.FloatField(default=0.1)),
                ('special_collision_cost', models.JSONField(default=None)),
                ('special_collision_constraint', models.JSONField(default=None)),
                ('collision_constraint_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.collisionconstraintconfig')),
                ('collision_cost_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.collisioncostconfig')),
            ],
            options={
                'db_table': 'trajopt_default_composite_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrajOpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_name', models.CharField(max_length=255)),
                ('profile_name', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('program', models.JSONField()),
                ('default_composite_profile', models.ManyToManyField(to='stats.trajoptdefaultcompositeprofile')),
                ('default_plan_profile', models.ManyToManyField(to='stats.trajoptdefaultplanprofile')),
                ('default_solver_profile', models.ManyToManyField(to='stats.trajoptdefaultsolverprofile')),
            ],
            options={
                'db_table': 'stat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('timer', models.FloatField()),
                ('joint_state_start_pose', models.IntegerField()),
                ('joint_state_finish_pose', models.IntegerField()),
                ('joint_state_middle_poses', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('params', models.JSONField()),
                ('obstacle_group_id', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('trajOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.trajopt')),
            ],
            options={
                'db_table': 'trajopt',
                'managed': True,
            },
        ),
    ]
